include:
- ${PWD}/services/rabbitmq/compose.yml
- ${PWD}/services/localstack/compose.yml
- ${PWD}/services/postgres/compose.yml
- ${PWD}/services/lambda/compose.yml

networks:
  local_network:
    ipam:
      config:
        - subnet: 10.5.0.0/16