services:
  ts-localstack:
    image: tailscale/tailscale
    container_name: ts-localstack
    hostname: localstack
    networks:
      local_network:
        ipv4_address: 10.5.0.11
    ports:
    - "127.0.0.1:4566:4566"            # LocalStack Gateway
    - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    env_file:
    - ../../.env
    volumes:
    - ./tailscale/state:/var/lib/tailscale
    devices:
    - /dev/net/tun:/dev/net/tun
    cap_add:
    - net_admin
    - sys_module

  localstack:
    image: localstack/localstack
    network_mode: service:ts-localstack
    environment:
    - SERVICES=ec2,iam,lambda,sts,s3,s3control  # Specify the services you want to use
    volumes:
    - ./localstack:/var/lib/localstack

volumes:
  ts-alpine:
    driver: local